name: mirror-awf

on:
  schedule:
    - cron: 0,30 * * * *
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mirror-awf:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out upstream repository
        uses: actions/checkout@v4
        with:
          repository: autowarefoundation/autoware_universe
          ref: main
          fetch-depth: 0 # preserve the entire history

      - name: Create replace message file
        run: |
          echo "regex:#(\d+)==>autowarefoundation/autoware_universe#\1" > /tmp/replace.txt
          cat /tmp/replace.txt
        shell: bash

      - name: Apply filter repo
        run: |
          sudo apt-get update && sudo apt-get install -y git-filter-repo
          git filter-repo --path visualization/ --path .github/ --path docs/ --path-regex '^[^/]*$' --replace-message /tmp/replace.txt --force
          git branch -m awf-latest
          git log --oneline
          git remote add downstream https://github.com/${{ github.repository }}.git
          git fetch downstream
        shell: bash

      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Set git config
        uses: autowarefoundation/autoware-github-actions/set-git-config@v1
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Push to downstream
        run: git push downstream awf-latest:awf-latest
        shell: bash
