name: mirror-e2e

on:
  schedule:
    - cron: 0,30 * * * *
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mirror-e2e:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out upstream repository
        uses: actions/checkout@v4
        with:
          repository: tier4/autoware_universe
          ref: feat/v0.64/e2e
          fetch-depth: 0 # preserve the entire history

      - name: Apply filter repo
        run: |
          sudo apt-get update && sudo apt-get install -y git-filter-repo
          git filter-repo --path visualization/ --path .github/ --path docs/ --path-regex '^[^/]*$' --commit-callback '
          BOUNDARY = 1771632000  # 2026-02-21T00:00:00Z (timezone does not matter here)
          date = int(commit.author_date.split()[0])
          if date < BOUNDARY:
              commit.message = re.sub(rb"#(\d+)", rb"autowarefoundation/autoware_universe#\1", commit.message)
          else:
              commit.message = re.sub(rb"(?<!autowarefoundation)(?<!autowarefoundation/autoware_universe)#(\d+)", rb"tier4/autoware_universe#\1", commit.message)
          ' --force
          git branch -m feat/v0.64/e2e
          git log --oneline
          git remote add downstream https://github.com/${{ github.repository }}.git
          git fetch downstream
        shell: bash

      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Set git config
        uses: autowarefoundation/autoware-github-actions/set-git-config@v1
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Push to downstream
        run: git push downstream feat/v0.64/e2e:feat/v0.64/e2e --force
        shell: bash
